(defun conta (lst)
  (let ((var 0))
    (do ((i 0 (+ i 1)))
      ((> i (list-length lst)) var)
     (if (eq (nth i lst) 'a)
       (+ var 1)
       'false))))

(defun other (lst)
  (let ((var 0))
    (dolist (obj lst)
      (if (eq obj 'a)
        (setf var (+ var 1))))
    var))
